### ISSUE TITLE
Unable to submit Inference workloads using quick start docs

### ISSUE THREAD

**Issue by mpaulgreen** [run-ai/docs#747]
Hi, I was trying to deploy inference workload using UI and as well as YAML. Here is the YAML. The example here was taken from quickstart guide for Run:ai 2.15 docs.
```
apiVersion: run.ai/v2alpha1
kind: InferenceWorkload
metadata:
  name: inference1
  namespace: runai-demo
spec:
  name:
    value: inference1
  gpu:
    value: "0.5"
  image:
    value: "gcr.io/run-ai-demo/example-triton-server"
  minScale:
    value: 1
  maxScale:
    value: 2
  metric:
    value: concurrency
  target:
    value: 80
  ports:
      items:
        port1:
          value:
            container: 8000
            protocol: http

```

I get the following error 
```
Error from server (validation failed: must not set the field(s): spec.template.spec.schedulerName, spec.template.spec.securityContext): error when creating "inferenceworkload.yaml": admission webhook "workload-controller.runai.svc" denied the request: validation failed: must not set the field(s): spec.template.spec.schedulerName, spec.template.spec.securityContex
```

This was done on openshift 4.13.
